# Generated by Django 6.1 on 2026-08-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo', models.TextField()),
                ('todo_dis', models.TextField()),
                ('todo_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
