# Generated by Django 6.1 on 2026-08-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='done',
            field=models.IntegerField(default=0),
        ),
    ]
